# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- master
variables:
- group: Variables
stages:
- stage: 'Build_Stage' #Stage name cannot have spaces
  displayName: 'Build' #Name displayed when viewing in Azure DevOps
  jobs:
  - job: 'Build_Job' #Job name cannot have spaces
    displayName: 'Application Build' #Name displayed when viewing in Azure DevOps
    pool:
      name: ProjectPool
  
    steps:
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(build.sourcesdirectory)'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/bootcamp.zip'
        replaceExistingArchive: true
      displayName: "Creating zip file and moving to agent's Artifact directory from source"

      
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)/bootcamp.zip' 
        artifactName: 'bootcamp-app'
      displayName: 'Publish Artifact'
      
    


- stage: 'Staging' #Stage name cannot have spaces
  variables:
  - group: envStage
  displayName: 'Staging' #Name displayed when viewing in Azure DevOps
  dependsOn: ['Build_Stage'] #List of previous stages that must complete before this stage runs
  jobs:
  - deployment: Deploy_Staging #No spaces
    displayName: Staging Deployment #Name displayed in UI
    pool:
      name: ProjectPool 
    environment: Staging
    strategy:
      runOnce:
        deploy:
          steps:
          - template: templates/CDTemplate.yaml


          
- stage: 'Production' #Stage name cannot have spaces
  variables:
  - group: envProd
  displayName: 'Production' #Name displayed when viewing in Azure DevOps
  dependsOn: ['Build_Stage', 'Staging'] #List of previous stages that must complete before this stage runs
  jobs:
  - deployment: Deploy_Production #No spaces
    displayName: Production Deployment #Name displayed in UI
    pool:
      name: ProjectPool #variable that was defined previously (not shown in this snippet)
    environment: Production
    strategy:
      runOnce:
        deploy:
          steps:  
           - task: DownloadBuildArtifacts@0
             inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'bootcamp-app'
              downloadPath: '$(System.ArtifactsDirectory)'        