# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- master
stages:
- stage: 'Build_Stage' #Stage name cannot have spaces
  displayName: 'Build' #Name displayed when viewing in Azure DevOps
  jobs:
  - job: 'Build_Job' #Job name cannot have spaces
    displayName: 'Application Build' #Name displayed when viewing in Azure DevOps
    pool:
      name: StagingPool
  
    steps:
    - template: templates/CITemplate.yaml
    
    


- stage: 'Staging' #Stage name cannot have spaces
  variables:
  - group: envStage
  displayName: 'Staging' #Name displayed when viewing in Azure DevOps
  dependsOn: ['Build_Stage'] #List of previous stages that must complete before this stage runs
  jobs:
  - deployment: Deploy_Staging #No spaces
    displayName: Staging Deployment #Name displayed in UI
    pool:
      name: StagingPool 
    environment: Staging
    strategy:
      runOnce:
        deploy:
          steps:
          - task: UniversalPackages@0
            inputs:
              command: 'download'
              downloadDirectory: '$(System.ArtifactsDirectory)'
              feedsToUse: 'internal'
              vstsFeed: '40a8d693-43e7-4d3c-b58e-d3cae2291e12/be6112bc-799a-41e4-909b-500909a53470'
              vstsFeedPackage: '4bb89539-7ba3-42e5-9f5c-b754ecf6e250'
              vstsPackageVersion: 'latest'

          - template: templates/CDTemplate.yaml


          
- stage: 'Production' #Stage name cannot have spaces
  variables:
  - group: envProd
  displayName: 'Production' #Name displayed when viewing in Azure DevOps
  dependsOn: ['Build_Stage', 'Staging'] #List of previous stages that must complete before this stage runs
  jobs:
  - deployment: Deploy_Production #No spaces
    displayName: Production Deployment #Name displayed in UI
    pool:
      name: ProductionPool #variable that was defined previously (not shown in this snippet)
    environment: Production
    strategy:
      runOnce:
        deploy:
          steps:  
          - template: templates/CDTemplate.yaml      